version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DUMP_FNAME
    ports:
      - "5432:5432"
    volumes:
      - ./docker.initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./dumps:/dumps
      - ./data:/var/lib/postgresql/data

networks:
  default:
    name: ${POSTGRES_DB}-network
